### ISSUE TITLE
Error in prepare.sh (postgres vs postgresql)

### ISSUE THREAD

**Issue by jknapp82** [boschkundendienst/guacamole-docker-compose#100]
First of all: Thanks for your work! Very usefull and great documentation. 

I had some problems with the installation
- relation "guacamole_user" does not exist errors
-finaly I got to initdb.sql, where I found an error message "Bad database type: postgresql", 

As soon as I changed that the docker run command in prepare.sh from "--postgresql" to "--postgres" everything works fine.

Is that a bug?

Thanks, BR Jochen

**Comment by fragstein84** [comment]
Hi,
You raised a doubt and I went to check on the Guacamole website.
It's not an error, it's '--postgresql'.
Here's the source
It has always worked for me.

[https://guacamole.apache.org/doc/gug/guacamole-docker.html](url)

_

> Initializing the PostgreSQL database
> If your database is not already initialized with the Guacamole schema, you will need to do so prior to using Guacamole. A convenience script for generating the necessary SQL to do this is included in the Guacamole image.
> 
> To generate a SQL script which can be used to initialize a fresh PostgreSQL database as documented in Database authentication:
> 
> docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > initdb.sql
>
> Alternatively, you can use the SQL scripts included with the database authentication.

**Comment by boschkundendienst** [comment]
just test on Linux and worked as expected. If there are still problems reopen and send more details. Operating system and version. What commands you exactly typed etc.

**Comment by jknapp82** [comment]
Thanks a lot for now! I do not have the time to analyse it now, but I will do soon.
Thanks again, BR Jochen
