### ISSUE TITLE
RDP server closed/refused connection: Server refused connection (wrong security type?)

### ISSUE THREAD

**Issue by soumoks** [boschkundendienst/guacamole-docker-compose#101]
I have enabled Guacamole using docker-compose and disabled nginx. Trying to RDP into a Fedora workstation but seem to be getting this error
```
guacd[1567]: INFO:	RDP server closed/refused connection: Server refused connection (wrong security type?)

```

I have tried all available authentication methods.

**Comment by lucasdellasantina** [comment]
Inside guacamole, when you go to configuration, connections, and configure your connection, you have to specify on the 'host name' the IP of your guacnetwork_compose gateway. In my case I was using an external bridge network as opposed to this compose's default  bridge, but you would only have to add
`ipam:
  driver: default
  config:
    - subnet: 172.22.0.0/16
      gateway: 172.22.0.1`
under the network definition of your guacnetwork_compose network, below the driver  directive.
      
And then tell guacamole to find your RDP/VNC Port on the 172.22.0.1 IP.
