### ISSUE TITLE
openid

### ISSUE THREAD

**Issue by lisandro2012** [boschkundendienst/guacamole-docker-compose#103]
Hi I wish to know if there is any procedure to add interfase for Authentik openid
thanks

**Comment by boschkundendienst** [comment]
Afaik you just have to configure an environment variable `GUACAMOLE_HOME` in the environment section of the `guacamaloe` container in the `docker-compose.yml` to point to `/opt/guacamole`. This should enable the extension inside the container.

The extension is present (verified)  in `docker.io/guacamole/guacamole:1.5.5` or `docker.io/guacamole/guacamole:latest`.

```ini
...
environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME=/opt/guacamole
...
```

After setting the environment variable you can configure OpenID as described in the official docs (also by environment variables, also added to the docker-compose.yml files guacamole container section).
[Configure Guacamole for SSO with OpenID Connect](https://guacamole.apache.org/doc/gug/openid-auth.html#configuring-guacamole-for-single-sign-on-with-openid-connect)

Just replace every lower-case setting described there with an environment variable in upper case and replace `-` with `_` e.g.

```
# as configuration parameter
openid-authorization-endpoint=https://identity-provider/.well-known/openid-configuration

# as environment variable
OPENID_AUTHORIZATION_ENDPOINT=https://identity-provider/.well-known/openid-configuration
```

The following variables seem to be present (verified inside the guacamole container)

```
OPENID_AUTHORIZATION_ENDPOINT
OPENID_JWKS_ENDPOINT
OPENID_ISSUER
OPENID_CLIENT_ID
OPENID_REDIRECT_URI
```

How to configure thinks on the **Authentik** side, I have no clue!

Just a hint, if you get it working, keep in mind, that this project is not intended to be run in production. For production use you should build your own setup and take security into mind, too.

For example at work I run Guacamole with rootless podman containers on RHEL.

Also it would be nice if you could update this issue, too.

**Comment by lisandro2012** [comment]
thank you!!!!!!!!!!!!!

**Comment by gonsaaa** [comment]
> thank you!!!!!!!!!!!!!

Did you managed to do it?
Can you share your configs?

**Comment by lisandro2012** [comment]
at last I didn't do it 
sorry

**Comment by gonsaaa** [comment]
> at last I didn't do it sorry

I manage to do it with traefik reverse proxy and proxy-auth in authentik.
like it is shown here:
https://youtu.be/N5unsATNpJk?t=2017
