### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by mortal2424** [boschkundendienst/guacamole-docker-compose#105]
Good afternoon, please tell me how to connect to the Active Directory server, where to insert the config lines so that users from Active Directory can be used. I don't understand how to do this

**Comment by boschkundendienst** [comment]
As you already might have found out, this is not part of this project. Look at the official documentation, especially the docker version with ldap at https://guacamole.apache.org/doc/gug/guacamole-docker.html#ldap-authentication
Also a good place for support is the [Guacamole Mailinglist](https://guacamole.apache.org/support/)
