### ISSUE TITLE
For other proxies use /guacamole, not /

### ISSUE THREAD

**Issue by jtagcat** [boschkundendienst/guacamole-docker-compose#13]
I burned more than an hour on this. Mention in the docker-compose and in the readme, that if not using nginx, use :8080/guacamole, not :8080/ as it's currently there.

**Comment by boschkundendienst** [comment]
Well, if you are an experienced user and knowing how to use something else instead of nginx you should probably also read the guacamole documentation first.
If you could clarify what exactly you find is or send a pull request I could take a closer look into it.

**Comment by LoganTann** [comment]
Another advice is to avoid using apache as reverse proxy for guacamole
websockets may not work unless touching your configuration (steps are explained in the docs)
