### ISSUE TITLE
Where is "guacenc"?

### ISSUE THREAD

**Issue by wisoez** [boschkundendienst/guacamole-docker-compose#17]
Screen recording file are in a raw Guacamole format. I will need to encode it to a video to be able to watch them. The guacamole format is not a video, and is extremley small.

There is a tool called "guacenc" included with Guacamole that you can use that makes it into a .m4v file. But i don't know where is "guacenc" in container?

Plz help me. Tk U!

**Comment by boschkundendienst** [comment]
Hi, @wisoez. Afaik the guacenc is not in the docker images.
I use the official docker images `guacamole/guacd` and `guacamole/guacamole`, so what is not in there I can not provide.

I could easily compile guacenc on Ubuntu 20.04 by following [this guide](https://kifarunix.com/install-apache-guacamole-on-ubuntu-20-04/) and using the [1.3 source](https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download).

Additionally to the mentioned dependencies, make sure you also install `libavformat-dev` because **"The guacenc utility, provided by guacamole-server to translate screen recordings into video, depends on FFmpeg, and will only be built if at least the libavcodec, libavformat, libavutil, and libswscale libraries provided by FFmpeg are installed."**

Then when doing a `./configure` you should at least see a **yes** for **guacenc** in the output

```
~/tmp/guacamole-server-1.3.0$ ./configure
...
...
------------------------------------------------
guacamole-server version 1.3.0
------------------------------------------------

   Library status:

     freerdp2 ............ yes
     pango ............... yes
     libavcodec .......... yes
     libavformat.......... yes
     libavutil ........... yes
     libssh2 ............. yes
     libssl .............. yes
     libswscale .......... yes
     libtelnet ........... yes
     libVNCServer ........ yes
     libvorbis ........... yes
     libpulse ............ yes
     libwebsockets ....... no
     libwebp ............. yes
     wsock32 ............. no

   Protocol support:

      Kubernetes .... no
      RDP ........... yes
      SSH ........... yes
      Telnet ........ yes
      VNC ........... yes

   Services / tools:

      guacd ...... yes
      guacenc .... yes
      guaclog .... yes
...
...
```

Then a `make` also should work and you should have the guacenc binary in `./src/guacenc/guacenc`.

Running it works now!

```
~/tmp/guacamole-server-1.3.0$ ./src/guacenc/guacenc
guacenc: INFO: Guacamole video encoder (guacenc) version 1.3.0
guacenc: INFO: No input files specified. Nothing to do.
```

**Comment by wisoez** [comment]
> Hi, @wisoez. Afaik the guacenc is not in the docker images.
> I use the official docker images `guacamole/guacd` and `guacamole/guacamole`, so what is not in there I can not provide.
> 
> I could easily compile guacenc on Ubuntu 20.04 by following [this guide](https://kifarunix.com/install-apache-guacamole-on-ubuntu-20-04/) and using the [1.3 source](https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download).
> 
> Additionally to the mentioned dependencies, make sure you also install `libavformat-dev` because **"The guacenc utility, provided by guacamole-server to translate screen recordings into video, depends on FFmpeg, and will only be built if at least the libavcodec, libavformat, libavutil, and libswscale libraries provided by FFmpeg are installed."**
> 
> Then when doing a `./configure` you should at least see a **yes** for **guacenc** in the output
> 
> ```
> ~/tmp/guacamole-server-1.3.0$ ./configure
> ...
> ...
> ------------------------------------------------
> guacamole-server version 1.3.0
> ------------------------------------------------
> 
>    Library status:
> 
>      freerdp2 ............ yes
>      pango ............... yes
>      libavcodec .......... yes
>      libavformat.......... yes
>      libavutil ........... yes
>      libssh2 ............. yes
>      libssl .............. yes
>      libswscale .......... yes
>      libtelnet ........... yes
>      libVNCServer ........ yes
>      libvorbis ........... yes
>      libpulse ............ yes
>      libwebsockets ....... no
>      libwebp ............. yes
>      wsock32 ............. no
> 
>    Protocol support:
> 
>       Kubernetes .... no
>       RDP ........... yes
>       SSH ........... yes
>       Telnet ........ yes
>       VNC ........... yes
> 
>    Services / tools:
> 
>       guacd ...... yes
>       guacenc .... yes
>       guaclog .... yes
> ...
> ...
> ```
> 
> Then a `make` also should work and you should have the guacenc binary in `./src/guacenc/guacenc`.
> 
> Running it works now!
> 
> ```
> ~/tmp/guacamole-server-1.3.0$ ./src/guacenc/guacenc
> guacenc: INFO: Guacamole video encoder (guacenc) version 1.3.0
> guacenc: INFO: No input files specified. Nothing to do.
> ```

Hi @boschkundendienst I am using "litios/guacenc" container for easy deploy :D

**Comment by boschkundendienst** [comment]
> > Hi, @wisoez. Afaik the guacenc is not in the docker images.
> > I use the official docker images `guacamole/guacd` and `guacamole/guacamole`, so what is not in there I can not provide.
> > I could easily compile guacenc on Ubuntu 20.04 by following [this guide](https://kifarunix.com/install-apache-guacamole-on-ubuntu-20-04/) and using the [1.3 source](https://apache.org/dyn/closer.lua/guacamole/1.3.0/source/guacamole-server-1.3.0.tar.gz?action=download).
> > Additionally to the mentioned dependencies, make sure you also install `libavformat-dev` because **"The guacenc utility, provided by guacamole-server to translate screen recordings into video, depends on FFmpeg, and will only be built if at least the libavcodec, libavformat, libavutil, and libswscale libraries provided by FFmpeg are installed."**
> > Then when doing a `./configure` you should at least see a **yes** for **guacenc** in the output
> > ```
> > ~/tmp/guacamole-server-1.3.0$ ./configure
> > ...
> > ...
> > ------------------------------------------------
> > guacamole-server version 1.3.0
> > ------------------------------------------------
> > 
> >    Library status:
> > 
> >      freerdp2 ............ yes
> >      pango ............... yes
> >      libavcodec .......... yes
> >      libavformat.......... yes
> >      libavutil ........... yes
> >      libssh2 ............. yes
> >      libssl .............. yes
> >      libswscale .......... yes
> >      libtelnet ........... yes
> >      libVNCServer ........ yes
> >      libvorbis ........... yes
> >      libpulse ............ yes
> >      libwebsockets ....... no
> >      libwebp ............. yes
> >      wsock32 ............. no
> > 
> >    Protocol support:
> > 
> >       Kubernetes .... no
> >       RDP ........... yes
> >       SSH ........... yes
> >       Telnet ........ yes
> >       VNC ........... yes
> > 
> >    Services / tools:
> > 
> >       guacd ...... yes
> >       guacenc .... yes
> >       guaclog .... yes
> > ...
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then a `make` also should work and you should have the guacenc binary in `./src/guacenc/guacenc`.
> > Running it works now!
> > ```
> > ~/tmp/guacamole-server-1.3.0$ ./src/guacenc/guacenc
> > guacenc: INFO: Guacamole video encoder (guacenc) version 1.3.0
> > guacenc: INFO: No input files specified. Nothing to do.
> > ```
> 
> Hi @boschkundendienst I am using "litios/guacenc" container for easy deploy :D

Nice! Good finding!
