### ISSUE TITLE
Hot to add a new VNC connection?

### ISSUE THREAD

**Issue by Ks89** [boschkundendienst/guacamole-docker-compose#19]
Hi, I'm not an expert of Guacamole.
Probably, this is a very stupid question.

I tried to download your project and started and it's working perfectly.
However, now I have a local docker container that exposes a vnc server on port 5900. How can I connect this container to guacamole?

thanks.

**Comment by boschkundendienst** [comment]
Hi,

you have to somehow make sure, that Guacamole can reach the VNC server. If the VNC server is also a docker container you might want to create a docker network that contains all containers, then connection should be possible.

But in the end this is not related to my project.

Great, that so far the guacamole part works.

Cheers
