### ISSUE TITLE
Is there a way to change use of Port 8443 in the event that Port is already in use?

### ISSUE THREAD

**Issue by bmullan** [boschkundendienst/guacamole-docker-compose#20]
In the README it says:

> Your guacamole server should now be available at https://ip of your server:**8443**/. 

NGINX is redirecting incoming Port 8443 to Port 443 but there's not a "hard" reason that 8443 can't be changed
to something else right?  

In my use-case I am already using Port 8443 for something else so the Dockerized Guacamole's attempt to use it also will fail.

_Is there a way to change the incoming port to something other than 8443 by specifying it as a docker-compose  parameter or in the .yml file?_

thanks
brian

**Comment by boschkundendienst** [comment]
just change 8443 to whatever you like in line 156 in `docker-compose.yml` 

before:

```
   - 8443:443
```

after:

```
   - 443:443
```
