### ISSUE TITLE
can't configure Device/Drive redirection to work 

### ISSUE THREAD

**Issue by bmullan** [boschkundendienst/guacamole-docker-compose#21]
I am using a **_Ubuntu Linux server with xrdp and MATE_** Desktop environment.

I've used non-Docker Guacamole for a couple years and always configured Drive redirection as below and its always worked.

However Guacamole-Docker-Compose's Guacamole it doesn't.

**Device Redirection**  
:  
:  
Enable drive:  **check-marked**  
Drive name:    **shared-drive**  
Disable file download:  
Disable file upload:  
Drive path:   **/home/${GUAC_USERNAME}**  
Automatically create drive:   **check-marked**
Static channel names:   **rdpdr**

But on my MATE desktop don't get a folder named **shared-drive** but a folder named the default **thinclient-drives**

and inside **thinclient_drives** there is the expected GUACFS directory.

But any attempt to copy a file to either folder fails:

> _**Error opening file “/home/bmullan/thinclient_drives/junk.txt”: No such file or directory**_  

So on my Mate Desktop server I edited XRDP's config:
  
**/etc.xrdp/sesman.ini** and manually changed the name in XRDP's config to **shared-drive** and that fixed the folder name issue as the folder on the Desktop is now named _**shared-drive**_

But any attempt to copy a file to that folder still fails fails:

> _**Error opening file “/home/bmullan/thinclient_drives/junk.txt”: No such file or directory**_

Since this is a Docker Guacamole I'm not sure how to even check some of the normal config files such as:

> /etc/guacamole/guacamole.properties

> /etc/guacamole/user-mapping.xml

The XRDP config file on my MATE Desktop server assume's a FUSE connection to the 

Per the Apache Guacamole documentation:

> Device redirection
> 
> Device redirection refers to the use of non-display devices over RDP. Guacamole's RDP support currently allows redirection of audio, printing, and disk access, some of which require additional configuration in order to function properly.
> 
> Audio redirection will be enabled by default. If Guacamole was correctly installed, and audio redirection is supported by your RDP server, sound should play within remote connections without manual intervention.
> 
> Printing requires GhostScript to be installed on the Guacamole server, and allows users to print arbitrary documents directly to PDF. When documents are printed to the redirected printer, the user will receive a PDF of that document within their web browser.
> 
> **_Guacamole provides support for file transfer over RDP by emulating a virtual disk drive. This drive will persist on the Guacamole server, confined within the drive path specified_**.
> 

I realize my target Desktop is MATE/Linux via XRDP and not Windows but I'd think this should still work correctly as before.

I did find this long thread on problems w/Docker and FUSE:
**[Docker for Linux - FUSE issues](https://github.com/docker/for-linux/issues/321)**

I also found:

**[New Features in Docker 20.10 - includes fuse-overlay-fs](https://medium.com/nttlabs/docker-20-10-59cc4bd59d37)**

> **Supports FUSE-OverlayFS**
> 
> Mounting OverlayFS without the root is not supported on most host operating systems except Ubuntu and Debian. So, Rootless Docker 19.03 running on a non-Ubuntu/non-Debian host could not deduplicate files using OverlayFS.
> 
> Docker 20.10 supports FUSE-OverlayFS, which is an unprivileged alternative for OverlayFS and works on any host with kernel ≥ 4.18.
> 
> Docker 20.10 automatically falls back into FUSE-OverlayFS when OverlayFS is not functional but FUSE-OverlayFS is functional.

Not being a knowledgeable Docker user though I'm not sure how to interpret all of this from the Docker point of view such as does it have to be enabled in the Docker container etc?

Any ideas why the FUSE connection to the Docker/Guacamole Server doesn't work?

**Comment by bmullan** [comment]
just fyi.. found out from the Guacamole Dev's that the Drive Redirection problem I was having was an xRDP bug that supposedly is fixed in a newer version of xRDP than I was using...

**https://lists.apache.org/thread/s99rf1zl1hrtfoqg6zkrvbl9ccb0zoj8**

**Comment by jxfruit** [comment]
May I ask how to map a few directories into virtualmachine? Now I find only one directory can be redirected into virtualmachine
