### ISSUE TITLE
404: The requested resource [/guacamole/] is not available

### ISSUE THREAD

**Issue by dekiesel** [boschkundendienst/guacamole-docker-compose#25]
Hi,

I am getting this error when connecting https://myip

```
HTTP Status 404 – nicht gefunden

Type Status Report

Message The requested resource [/guacamole/] is not available

Beschreibung The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
Apache Tomcat/9.0.43
```

I didn't change the config and nginx is working correctly (I think) because I am being forwarded to tomcat.

Thank you for your help!

**Comment by boschkundendienst** [comment]
My configuration exposes Guacamole to `/` and on port 8443 via https. So the correct URL is `https://<yourip>:8443/`.

This should work without problems.

**Comment by dekiesel** [comment]
Sorry, I forgot to add the `8443` in my comment, but I didn't in my actual call:

`https://myip:8443/`

leads to the abovementioned error.

As I said, the error is a tomecat error so the call must have gotten to nginx which means I at least got the url to nginx right.

**Comment by dekiesel** [comment]
Uncomment the lines for the direct tomcat access in `docker-compose.yaml` also shows the same error.

I.e. when I navigate to: `http:myip:8080/guacamole`

**Comment by boschkundendienst** [comment]
@dekiesel I immediately tried on my test machine. I followed exactly the howto in the README.md and it worked immediately.

Did you forge something like the ./prepare.sh command?

Please exactly follow https://github.com/boschkundendienst/guacamole-docker-compose#readme .

What I did to verify


- docker and docker-compose installed and running (on Manjaro)
- my user is within the group docker
- cloned the git repo and cd into `guacamole-docker-compose` folder
- run `./prepare.sh`
- run `docker-compose up -d`
- Open https://127.0.0.1:8443 in browser <- just worked

What Linux distribution and what version of docker are you using?
