### ISSUE TITLE
docker compose password special characters

### ISSUE THREAD

**Issue by davidfrankks** [boschkundendienst/guacamole-docker-compose#29]
Put single quotes around your password, otherwise special char will cause the docker-compose.yml file to fail with str errors.
POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234!!!$$$@@@'

**Comment by boschkundendienst** [comment]
fixe in this [commit](https://github.com/boschkundendienst/guacamole-docker-compose/commit/c0d9571abd4ffcd34f0113a6f25b294258cb9de7)
