### ISSUE TITLE
NGinx and Postgress docker containers - consistently restarting.

### ISSUE THREAD

**Issue by Dratnet** [boschkundendienst/guacamole-docker-compose#34]
Hello,

I'm opening this issue to bring to light a problem I had. May be that I'm new to SELinux policies...but err, anyways.

On CentOS7 and CentOS8, while using the base security policy (SELinux), the docker containers for NGinx and Postgress consistently restart and do not ever launch fully.

nginx_guacamole_compose Logs:

> 2022-04-20T02:25:44.545918000Z 2022/04/20 02:25:44 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
> 2022-04-20T02:25:44.546611000Z nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)

postgres_guacamole_compose Logs:

> ```
> 2022-04-20T02:38:25.453551000Z mkdir: cannot create directory ‘/var/lib/postgresql/data/guacamole’: Permission denied
> 2022-04-20T02:38:26.942927000Z mkdir: cannot create directory ‘/var/lib/postgresql/data/guacamole’: Permission denied
> ```

/var/log/audit/audit.log Logs:

> type=AVC msg=audit(1650422854.189:2327): avc:  denied  { read } for  pid=24165 comm="nginx" name="nginx.conf" dev="dm-0" ino=68409794 scontext=system_u:system_r:container_t:s0:c88,c837 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422854.189:2327): avc:  denied  { open } for  pid=24165 comm="nginx" path="/etc/nginx/nginx.conf" dev="dm-0" ino=68409794 scontext=system_u:system_r:container_t:s0:c88,c837 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422855.281:2334): avc:  denied  { read } for  pid=24270 comm="psql" name="initdb.sql" dev="dm-0" ino=33898998 scontext=system_u:system_r:container_t:s0:c42,c397 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422855.281:2334): avc:  denied  { open } for  pid=24270 comm="psql" path="/docker-entrypoint-initdb.d/initdb.sql" dev="dm-0" ino=33898998 scontext=system_u:system_r:container_t:s0:c42,c397 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422887.887:2484): avc:  denied  { read } for  pid=25303 comm="nginx" name="nginx.conf" dev="dm-0" ino=68409794 scontext=system_u:system_r:container_t:s0:c88,c837 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422887.887:2484): avc:  denied  { open } for  pid=25303 comm="nginx" path="/etc/nginx/nginx.conf" dev="dm-0" ino=68409794 scontext=system_u:system_r:container_t:s0:c88,c837 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
> type=AVC msg=audit(1650422889.085:2489): avc:  denied  { read } for  pid=24618 comm="postgres" name="global.stat" dev="dm-0" ino=100880705 scontext=system_u:system_r:container_t:s0:c42,c397 tcontext=system_u:object_r:user_home_t:s0 tclass=file permissive=1

Solution:
AVC denial messages indicates container_t is not a permissive domain, therefore is not possible to write (13: Permission denied). In order to resolve this issue, add container_t in the SELinux.

> 
> 1) semanage permissive -a container_t
> 2) semodule -l | grep permissive
>        Output:
>              permissive_container_t (null)
>              permissivedomains (null)

After doing so, killing the docker containers (docker-compose down)
Reset data:  ./reset.sh
prep SSL certs for Nginx: ./prepare.sh
Then bring the containers back up: docker-compose up -d

Worked like a charm, but took some digging. Thanks for the phenomenal work!

**Comment by boschkundendienst** [comment]
Hi, thanks for bringing this up. Could you provide the location of your files on disk? I never had problems with SELinux when cloning the repo to my home folder and running everything from there. I also always never run as root, instead I add my "sudo user" to the docker group. Would be nice to get some feedback.

**Comment by mvanorder** [comment]
I have this issue on CentOS 7 while selinux is enforcing.  The issue where you can't access anything as the root user is mentioned in [docker-library/postgres issue #884](https://github.com/docker-library/postgres/issues/884) and on [stackoverflow](https://stackoverflow.com/questions/69706677/cannot-start-postgresql-docker-container-docker-entrypoint-initdb-d-oper).  Using the postgres:13.4-buster fixes the ability to access the container's filesystem at all.  However it doesn't allow you to access the volumes while selinux is enforcing.  In order to do that you have to use the z/Z modes rather than ro/rw modes.
