### ISSUE TITLE
Can not configure server.xml

### ISSUE THREAD

**Issue by paultroeger** [boschkundendienst/guacamole-docker-compose#44]
Hello, 

I am having trouble with configuring the Remote IP Valve like described in the official config here:
https://guacamole.apache.org/doc/gug/reverse-proxy.html

The file exists in `/home/guacamole/tomcat/conf/server.xml` inside the docker container.
Making changes to it via docker exec doesn't work since guacamole would need to be restarted. 

I've also tried mounting the file like this:
```
volumes:
  - ./server.xml:/home/guacamole/tomcat/conf/server.xml
```
but then guacamole doesn't start since the created file systems cannot be accessed due to permission problems. 

Another thing I tried is setting up a `GUACAMOLE_HOME` folder via volumes. But as far as I understand it changes in that folder do not carry over to `conf/server.xml`

Does someone know how to modify the `docker-compose.yml` to be able to edit `server.xml`?

Best,
Paul

**Comment by boschkundendienst** [comment]
Hi Paul, I think I get what you are trying to achieve but this is way beyond the purpose of this project. It is just a demonstration to be able to setup Guacamole very fast but if you have special configuration needs, you should consider creating the project from scratch and use your own configuration settings and modifications.

Regards

Peter
