### ISSUE TITLE
Nginx Container restart looping

### ISSUE THREAD

**Issue by LazyKB** [boschkundendienst/guacamole-docker-compose#47]
Just ran the script with the quick start instructions on this page. It looks like theres a problem with the certificate happening when I have a look at the docker logs for the Nginx container. Here is the log. I am running this from an Alpine LXC container.

`Guac:~/guacamole-docker-compose# docker logs nginx_guacamole_compose
2022/10/20 22:45:37 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:39 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:40 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:42 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:43 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:45 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:48 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:45:55 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
2022/10/20 22:46:08 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/self.cert": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)`

**Comment by boschkundendienst** [comment]
Hi, did you run [prepare.sh](https://github.com/boschkundendienst/guacamole-docker-compose/blob/master/prepare.sh) before starting the container? It looks like you did not. `prepare.sh` will generate the needed certificates that nginx uses.
