### ISSUE TITLE
GUACAMOLE_HOME configuration

### ISSUE THREAD

**Issue by charliematar** [boschkundendienst/guacamole-docker-compose#5]
I created the `GUACAMOLE_HOME` directory (located in `/Users/myuser`)  but am having trouble pointing the `guacamole_compose` container to it. I have `GUACAMOLE_HOME` set as an Environment Variable `Key` and the `Value` is set as the path, `/Users/myuser` but upon restarting the container the message `cp: cannot stat '/Users/myuser/.': No such file or directory` appears. 

I need this directory to add extensions to guacamole.

I am new to Docker and Gaucamole so any advice helps. Thanks!

**Comment by boschkundendienst** [comment]
This repo is a fully self contained guacamule for easy testing. But you could maybe achieve what you want to do by exposing the folder from the containers by adding them to the yml file.
