### ISSUE TITLE
Cant Reach from Outside

### ISSUE THREAD

**Issue by MarcusFfm** [boschkundendienst/guacamole-docker-compose#53]
Hey , thank you for the Work.

I have a similar Installation,  there is a Guacd.conf   .To reach the Guac from outside i Change the hostname to public IP and can reach.

In this Installation i dont find this File. 
Not real an issuse ;/

**Comment by boschkundendienst** [comment]
what do you mean by "from outside"? With my setup (by the way only ment for testing purposes and not for production use) you can either connect to Guacamole on port 8443 (having the nginx container in front) or change `docker-compose.yml` to not use nginx which will then directly export port 8080 from the guacamole container.
I perfectly can run this setup "from outside" e.g. public internet.

**Comment by MarcusFfm** [comment]
Yeah i mean the Public Internet , sorry i am just trainee in the First year :)
Thx
