### ISSUE TITLE
MySQL version forthcoming?

### ISSUE THREAD

**Issue by n3gwg** [boschkundendienst/guacamole-docker-compose#54]
Developers,

Are there any plans to create a variant of this docker-compose that leverages MySQL instead of PostgreSQL?

Stuart

**Comment by boschkundendienst** [comment]
Since all the documentation how to use MySQL is available at the official Guacamole homepage and this project is not related to them I would say "No". Feel free to add a mysql container instead of postgres to your docker setup and with some slight modifications it will work.
