### ISSUE TITLE
Scripts (prepare and reset) fail in Windows

### ISSUE THREAD

**Issue by jorbig** [boschkundendienst/guacamole-docker-compose#56]
I would love to use your method of installing Guacamole, but I'm having trouble using it on Windows (I'm using Docker Desktop with WSL2). Bringing up the containers works fine, but the scripts throw some errors (even with Git for Windows installed). This doesn't matter for the reset.sh script, since I know how to delete some folders, but how to fix this error that prepare.sh gives me:

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start containuacamole/bin/initdb.sh": stat C:/Program Files/Git/opt/guacamole/bin/initdb.sh: no such file or directory: unknown.
```

That error is shown after this command in prepare.sh:

```
docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql
```

Any clue on what to do?

**Comment by boschkundendienst** [comment]
Maybe it has something to do with Windows. What should happen is, that the prepare script or let's say the command `docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > ./init/initdb.sql` should pull the guacamole/guacamole image from docker and then execute `/opt/guacamole/bin/initdb.sh --postgres` inside the container while outputing the result to the local file `./init/initdb.sql`
On Linux I found out, that `init.sql` must be flagged executable which you might not be able to achieve on Windows since that flag is not available on NTFS. 
Your error message states that "something" wants to execute `init.sh` in Windows since it shows a path containing `C:\Program Files\...`
I think I need more insights to be able to help you since I think you did a lot of stuff manually but maybe we could finally achieve creating a `prepare.bat` and `reset.bat` so one can use everything on Windows, too?
If I have time and a VM lying arround I would maybe try it on Windows.
What maybe could work is running everything with WSL2 but also did not test that, yet.

**Comment by jorbig** [comment]
Running the command in a WSL2 console didn't work, it returned the error:

`The command 'docker' could not be found in this WSL 2 distro.`

But then I got this crazy idea to ask the infamous ChatGPT to write me a Windows batch version of your scripts. That totally did the job!

Prepare.bat:
```
@echo off
REM check if docker is running
docker ps >nul 2>&1
if %errorlevel% neq 0 (
    echo docker daemon not running, will exit here!
    exit /b
)

echo Preparing folder init and creating .\init\initdb.sql
mkdir init >nul 2>&1
mkdir nginx\ssl >nul 2>&1
docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > init\initdb.sql
echo done
echo Creating SSL certificates
openssl req -nodes -newkey rsa:2048 -new -x509 -keyout nginx\ssl\self-ssl.key -out nginx\ssl\self.cert -subj "/C=DE/ST=BY/L=Hintertupfing/O=Dorfwirt/OU=Theke/CN=www.createyourown.domain/emailAddress=docker@createyourown.domain"
echo You can use your own certificates by placing the private key in nginx\ssl\self-ssl.key and the cert in nginx\ssl\self.cert
echo done
```

Reset.bat:
```
@echo off
echo This will delete your existing database (.\data\)
echo          delete your recordings        (.\record\)
echo          delete your drive files       (.\drive\)
echo          delete your certs files       (.\nginx\ssl\)
echo.
set /p answer=Are you sure? (Y/N)
if /I "%answer%" EQU "Y" (
  echo Doing dangerous stuff...
  echo.
  pushd .
  cd init
  popd
  rmdir /S /Q data drive record nginx\ssl
) else (
  echo Not doing anything.
)
```

Now I've got everything up and running! Hope this will save you (and others) some time.
And many thanks for your initial efforts to make this possible.

**Comment by boschkundendienst** [comment]
Nice job! Based on your comments you have docker desktop installed and use the WSL2 backend which does not require to have docker installed inside a WSL2 Linux distro. Docker desktop manages to have the docker executables available to windows directly (e.g. within cmd.exe or powershell.exe) and uses the WSL backend if needed.

Nice job by ChatGPT. Could you just tell me if those batch files work as intended? Is the following process possible with them?

```
git clone https://github.com/boschkundendienst/guacamole-docker-compose.git
cd guacamole-docker-compose
./prepare.bat
docker-compose up -d
```

If it would work like this I will add the batch files to the repo.

**Comment by boschkundendienst** [comment]
especially I think the `pushd`  and `popd`  command in `reset.bat`  won't work and needs to be fixed by something similar, maybe using `subst` somehow.

**Comment by jorbig** [comment]
Yes, it works as intended, except that:
- The command 'git' isn't available without external software like Git for Windows. So maybe it's better to just download and extract the ZIP on the Github page?
- The same goes for openssl. I don't use that, and didn't use the NGINX, because I use cloudflare(d) to automatically take care of SSL.
- As you can see I removed the chmod commands. ChatGPT left some of them in, but when I told it: "You should only exclude all chmod instances", it replied: "you're right, since chmod is a Unix command and is not available in Windows, you can exclude all instances of chmod in the batch file. I apologize for the oversight in my previous message."

What is the function of pushd and popd here, if no chmod takes place? Those commands are supported though in CMD.
