### ISSUE TITLE
permission denied when trying to change password

### ISSUE THREAD

**Issue by maxwellcheng** [boschkundendienst/guacamole-docker-compose#58]
i followed the quick start guide to run the guacamole-docker, 
i always get a permission denied error when trying to change password for the default account "guacadmin"...
I tried chmod 777 ./data/guacamole -R , create the dir (  mkdir -p ./data/guacamole) before running ./prepare.sh...
nothing works, 
and the log from docker logs-f  guacamole_compose  seems quite normal...
any help would be appreciated.
Thanks

**Comment by boschkundendienst** [comment]
this is by Design. You have to Create a new administrative account then logon with that one.
Now You Can Change the Password of guacadmin or delete it and work with the new one.
