### ISSUE TITLE
How to setup RDP and vnc IPv6 connection

### ISSUE THREAD

**Issue by babinem** [boschkundendienst/guacamole-docker-compose#62]
i deployed application on IPv6 and its working fine but when i want to add new connection RDP or VNC in ipv6 its not working.

**Comment by boschkundendienst** [comment]
Hi, this is not part of this project. Feel free to contact the authors of guacamole at https://guacamole.apache.org/support/

**Comment by boschkundendienst** [comment]
Maybe this could point you in the correct direction:
https://stackoverflow.com/questions/66090810/docker-compose-expose-port-on-ipv6
