### ISSUE TITLE
default hostname in this config

### ISSUE THREAD

**Issue by eggmister** [boschkundendienst/guacamole-docker-compose#68]
Firstly, thanks for this config script it has helped get me setup with about 5 hours of learning on guacamole, trying different repos, changing variables and working out how everything works. i don't know a lot about docker yet, but lots around general networking

One suggestion for change:
I've struggled to get the ui to connect to the daemon
had to manually set the hostname of the guacd container to guacd
this could be accomplished in the config, e.g. 
```
services:
  guacd:
    hostname: guacd
```

this would mean that when the services get different up addresses within their seperate containers in this stack, that the guacd one is given the right hostname that matches the default guacamole client configuration and everthing is a lot easier!

**Comment by boschkundendienst** [comment]
Hi, thanks for your feedback. I do not understand why you "struggled" to get the UI connect to the daemon. It does it "automagically" that's the whole purpose why I created this project.

Concerning your suggestion of adding a hostname to guacd. This is possible but with docker all containers are automatically reachable with their servicename which is already "guacd" for the guacd service. I don't understand why I should add that.

It seems to me you used my setup as a base and then changed it to your needs?
