### ISSUE TITLE
PSQLException: The authentication 10 is not supported.

### ISSUE THREAD

**Issue by stephzero1** [boschkundendienst/guacamole-docker-compose#70]
This is ithe output of `docker logs guacamole_compose`:
![immagine](https://github.com/boschkundendienst/guacamole-docker-compose/assets/25548571/e34f6f58-4641-445c-94dd-b1bc04f60575)

And this is the home page:
![immagine](https://github.com/boschkundendienst/guacamole-docker-compose/assets/25548571/b798f6b2-7804-4f17-9e4a-d16e15975492)

I just followed the guide for the first time.

Any hint? Thank everyone!

**Comment by boschkundendienst** [comment]
Tested 5 minutes ago. Works as expected. I assume you forget to run ./prepare.sh or did not read the docs.

**Comment by nath67** [comment]
I have the same issue.
I read the docs and I fixed ./prepare.sh because "--postgresql" is not working and I replace it with "--postgres".
