### ISSUE TITLE
session recording with apache guacamole

### ISSUE THREAD

**Issue by rajburnwal07** [boschkundendienst/guacamole-docker-compose#71]
I have tried to setup apache guacamole using docker setup.  but I am not able to enable session recording on the same setup. I have put session recording jar in extensions and created /var/lib/guacamole/recordings ( default path for recording) in guacamole client container. Now it seems I have to give similar permission in guacd container as well. And also documentation is missing on docker setup. did you try setting up session recording using guacamole?

**Comment by boschkundendienst** [comment]
not supported in this project. Recording works but needs a lot of configuration. Look at the official docker documentation from the Guacamole project.
