### ISSUE TITLE
Database Creation in prepare.sh incorrect

### ISSUE THREAD

**Issue by an0wak** [boschkundendienst/guacamole-docker-compose#72]
Hi,
Was using an older version of your docker-compose guac (no issues!!), recently decided to upgrade.

Found following line incorrect under prepare.sh
```
docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > ./init/initdb.sql
```

The file **initdb.sql** gets created but it has the following output.
```
Bad database type: --postgres
USAGE: /opt/guacamole/bin/initdb.sh [--postgresql | --mysql | --sqlserver]
```

May need to update this to.
```
docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgresql > ./init/initdb.sql
```

**Comment by boschkundendienst** [comment]
fixed now in prepare.sh, thanks for reporting seems guacamole changed something there.
