### ISSUE TITLE
Change in the "docker-compose.yml" POSTGRES_HOSTNAME detected, please use POSTGRESQL_HOSTNAME

### ISSUE THREAD

**Issue by Zakspeed** [boschkundendienst/guacamole-docker-compose#77]
Hi;

It is necessary to change in the "docker-compose.yml"
POSTGRES_HOSTNAME detected, please use POSTGRESQL_HOSTNAME

```
WARNING: POSTGRES_HOSTNAME detected, please use POSTGRESQL_HOSTNAME for further deployments.
WARNING: POSTGRES_DATABASE detected, please use POSTGRESQL_DATABASE for further deployments.
WARNING: POSTGRES_USER detected, please use POSTGRESQL_USER for further deployments.
WARNING: POSTGRES_PASSWORD detected, please use POSTGRESQL_PASSWORD for further deployments.
```

Good Job!!!
Thx

**Comment by boschkundendienst** [comment]
The error message comes from Guacamole which still uses the "old" variables internally. Changing them now will break it. We have to wait until the next guacamole docker release interprets the "new" variables correctly, then it can be fixed. Currently it is "only" a warning and does not hurt.
