### ISSUE TITLE
How to get the screen-recording extension to work with this install

### ISSUE THREAD

**Issue by adeelusman0** [boschkundendienst/guacamole-docker-compose#78]
This is not an issue but a solution to one that a lot of people here are facing, so I thought i'd share the steps that worked for me.

I will assume you have figured how to place the .jar file in the extensions folder as that has been thoroughly documented.

Firstly we need to find the UUID of the guacd and guacamole container. 

`[root@machine]# docker exec -it _guacd_container_ id

uidEdit the “Screen Recording” section of one of your existing connection settings. Enter the special value ${HISTORY_PATH}/${HISTORY_UUID} in the “Recording path” input box.

Check the “Automatically create recording path” box.

=1000(guacd) gid=1000(guacd) groups=1000(guacd)`

`
[root@machine]# docker exec -it _guacamole_container_ id

uid=1001(guacamole) gid=1001(guacamole) groups=1001(guacamole)

`

After getting the UUID, we need to assign these permissions to the docker volume _record_ which can typically be found in: /var/lib/docker/volumes/guac_record:

`
chown -R 1000:1001 /var/lib/docker/volumes/guac_record
chmod -R 2750 /var/lib/docker/volumes/guac_record

`

After this update the docker-compose.yml file and attach the same volume to both guacd and guacamole services like so:

`
# services
services:
  # guacd
  guacd:
    [...]
    volumes:
    - ./drive:/drive:rw
    - ./record:/var/lib/guacamole/recordings:rw 
 `
`
# guacamole
  guacamole:
    [...]
    environment:
      [...]
      GUACAMOLE_HOME: '/opt/guacamole_home'
    [...]
    volumes:
    - ./guacamole_home:/opt/guacamole_home
    - ./record:/var/lib/guacamole/recordings:ro
`

Please note the permissions for the volume for the service guacd is **rw** and for guacamole is **ro**.

After updating the docker-compose file please stop and redeploy the service. 

Edit the “Screen Recording” section of one of your existing connection settings. Enter the special value ${HISTORY_PATH}/${HISTORY_UUID} in the “Recording path” input box.

Check the “Automatically create recording path” box.

Now you should be able to see the view link in the logs column in the history tab.

Hope this helps as I was stuck on this forever.

**Comment by adeelusman0** [comment]
Messed up the steps

**Comment by adeelusman0** [comment]
This is not an issue but a solution to one that a lot of people here are facing, so I thought i'd share the steps that worked for me.

I will assume you have figured how to place the .jar file in the extensions folder as that has been thoroughly documented.

Firstly we need to find the UUID of the guacd and guacamole container.

`[root@machine]# docker exec -it guacd_container id

uid=1000(guacd) gid=1000(guacd) groups=1000(guacd)`

`
[root@machine]# docker exec -it guacamole_container id

uid=1001(guacamole) gid=1001(guacamole) groups=1001(guacamole)

`

After getting the UUID, we need to assign these permissions to the docker volume record which can typically be found in: /var/lib/docker/volumes/guac_record:

`
chown -R 1000:1001 /var/lib/docker/volumes/guac_record
chmod -R 2750 /var/lib/docker/volumes/guac_record

`

After this update the docker-compose.yml file and attach the same volume to both guacd and guacamole services like so:

`

services
services:

guacd
guacd:
[...]
volumes:
- ./drive:/drive:rw
- ./record:/var/lib/guacamole/recordings:rw
 

guacamole
guacamole:
[...]
environment:
[...]
GUACAMOLE_HOME: '/opt/guacamole_home'
[...]
volumes:
- ./guacamole_home:/opt/guacamole_home
- ./record:/var/lib/guacamole/recordings:ro
`

Please note the permissions for the volume for the service guacd is rw and for guacamole is ro.

After updating the docker-compose file please stop and redeploy the service.

Edit the “Screen Recording” section of one of your existing connection settings. Enter the special value ${HISTORY_PATH}/${HISTORY_UUID} in the “Recording path” input box.

Check the “Automatically create recording path” box.

Now you should be able to see the view link in the logs column in the history tab.

Hope this helps as I was stuck on this forever.

**Comment by weiyuDatawiza** [comment]
FYI
I need to add
`RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings`
in `environment` of `guacamole_compose`
https://github.com/apache/guacamole-client/blob/master/guacamole-docker/bin/start.sh#L950
