### ISSUE TITLE
Can't Connect to VNC

### ISSUE THREAD

**Issue by Naude555** [boschkundendienst/guacamole-docker-compose#79]
Good day i have followed this installation but am having trouble connecting through VNC. I have no trouble connecting through RDP and SSH.  
In the logs i get this error

Exception in thread "Thread-96" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed

Can you maybe point me in a direction 
I saw these post on StackOverflow
https://stackoverflow.com/questions/75656787/guacamole-websocket-error-java-lang-illegalstateexception
As well as 
https://stackoverflow.com/questions/76190681/apache-guacamole-totp-log

But was left more confused.

The connection screen also shows 
![image](https://github.com/boschkundendienst/guacamole-docker-compose/assets/60476722/1e635f00-7dfb-40da-b0bc-cbd03297c387)

That left me wondering if it was trying to connect through RDP. I checked my settings and it is set to VNC. 

Any help would be of great value.

**Comment by boschkundendienst** [comment]
Hi,
since I use the official Guacamole images please discuss such problems directly within the guacamole mailing list. The problem is not related to my project. Most of the times firewalls or incompatible vnc protocol implementations are the problem.

Regards

Peter
