### ISSUE TITLE
Restarted nginx, cannot connect anymore

### ISSUE THREAD

**Issue by sahara101** [boschkundendienst/guacamole-docker-compose#80]
Hello, guacamole was running fine and I restarted nginx container. Now, it stopped working:

2023/07/25 14:23:42 [error] 37#37: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/2.0", upstream: "http://192.168.1.150:8348/guacamole/", host: "192.168.1.150:8443"
172.20.0.1 - - [25/Jul/2023:14:23:42 +0000] "GET / HTTP/2.0" 502 497 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15" "-"

without nginx it is working fine. It worked until restart with the 8348 port, as I already have a container with 8080.

Thanks!

**Comment by sahara101** [comment]
Seems to be easier to change the other container to another port and to let guacamole on 8080

**Comment by boschkundendienst** [comment]
Hi, thanks for your feedback.
I think you have a problem understanding the concepts of docker.

A docker container that exposes network services always uses a port (internally only inside the docker container).

And there is the port that you want to show to the outside world. This port can be mapped to the internal port the
container uses.

One of the syntaxes in docker-compose.yml to map ports is like this:

**Expose ports without publishing them to the host machine - they’ll only be accessible to linked services. Only the internal port can be specified.**

```
  - "3000"
```

So this means, the container internally uses port 3000 (without exposing it to the outside world).

Also there is this syntax where you specify both ports (HOST:CONTAINER). So you specify which port is used internally (CONTAINER) and externally (HOST)

so

```
- 8443:443
```

means, there is a container that listens internally on 443 and at the host level it is port 8443. So when you connect to 8443 on the host you will land inside the container on 443.

If you put your containers on different docker networks I see absolutely no problem that guacd listens on 8080 while another service in another container in another docker network also listens on 8080. You only have to have different ports at the host level.

You know, my setup is only a demo.

What I would do in your case is to create a reverse proxy front-end e.g. nginx-proxy-manager and set it up.

Then I would run guacamole (guacd/mariadb/etc) and only expose the guacd port e.g. (- 8888:8080) to nginx-proxy-manager.

Then I would route https://whatever.tld to nginx-proxy-manager and nginx-proxy-manager would route that request to 8888/http which then lands on 8080/tcp inside the container.

In general I would not use my setup in a complex docker environment, I would create my own docker-compose.yml without nginx and would export only the guacd port to a reverse-proxy in front.

I hope I understood your problem and could provide some help.

Kind regards.

Peter
