### ISSUE TITLE
NGINX CONFIGURATION

### ISSUE THREAD

**Issue by nwf00** [boschkundendienst/guacamole-docker-compose#82]
Hi, I'n new at this

I could install  it.  
How can I configure NGINX and letsencrypt with a DDNS ? 
what version of guacamole? 
Can I use branding,jar?

Thanks

**Comment by boschkundendienst** [comment]
Hi, that are questions not covered by my project but well documented in the official guacamole and nginx documentation. Please  read the corresponding instructions on the respective project websites.

Just as a note. If I would be in your shoes, I would entirely disable nginx in the docker-compose.yml file. Then I would run nginx-proxy-manager and let your public DDNS point to it (port 80 and 443) and then I would configure a forward in nginx proxy manager to guacamole:8080. nginx-proxy-manager could then automatically retrieve a certificate from let
s encrypt.

But this is not as simple as it seems and your questions show me that it might be a bit too complicated for you.

Greets
Peter
