### ISSUE TITLE
How to use keytool to store CA for LDAPS

### ISSUE THREAD

**Issue by mattg66** [boschkundendienst/guacamole-docker-compose#85]
Hi, when using the LDAP authentication extension, is it possible to utilise the Java Key Store inside the guacamole container to store our CA certificate so we can use LDAPS?
Please can you advise on how to make this persistent,
Cheers

**Comment by boschkundendienst** [comment]
Hi, I am not an official of the Guacamole Project. You should ask at their site or on their mailing list.
