### ISSUE TITLE
Slight instruction issue in docker-compose.yml

### ISSUE THREAD

**Issue by ministic2001** [boschkundendienst/guacamole-docker-compose#87]
in `docker-compose.yml` line 23
`#  'docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > ./init/initdb.sql'`
the command should be `--postgresql` instead

I know this is correct in `prepare.sh`, but thought to put it here since I only read the docker-compose.yml and for others who also just go straight to the instruction in `docker-compose.yml`

**Comment by boschkundendienst** [comment]
thanks for the  info. file is updated at line 23.
