### ISSUE TITLE
Can't connect to vm windows 11?

### ISSUE THREAD

**Issue by Kreijstal** [boschkundendienst/guacamole-docker-compose#89]
This vm has:
- firewall disabled completely (to test this bug)
- NLA disabled.

I can connect with it using ssh from guacamole.
I can use freerdp and windows rdp from other computers in the network. using vinagre, xfreerdp, wfreerdp, sdl-freerdp, afreerdp (android) and mstsc. But guacd can't connect. 

Windows logs: says: the server security layer detected an error (0x80090304);
Guacamole says: RDP server closed/refused connection: Server refused connection (wrong security type?)

In settings I ignore certificates, and negotiate to any auth.
Guacd can however connect to xrdp servers, ssh servers, and vnc servers. Configuration is:
Linux host, windows 11, and linux host running the docker, they are in bridged connection, not sure if it matters, but all computers in network can see this vm.

**Comment by boschkundendienst** [comment]
Hi Kreijstal, thanks for using my project. All the "bugs" you might have found are not related to my project. I only create some files to be able to use the official docker images provided by the Guacamole project in an easy way. If you have any problems related to the Guacamole project itself (and your description looks like this), feel free to contact them over their [official support channel](https://issues.apache.org/jira/browse/GUACAMOLE/)

Kind regards

Peter
