### ISSUE TITLE
error when open url

### ISSUE THREAD

**Issue by changchichung** [boschkundendienst/guacamole-docker-compose#9]
I just clone this repo , and change nothing , just run prepare.sh and docker-compose up -d
containers runs ok , but when I try to open https://my_ip:8443  
there's an error message , even I dont have a chance to enter id and password ...
```
An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs.
```

and docker-compose logs show many messages , I paste to pastedbin
https://pastebin.com/e4HctqQx

something catch my eyes .
```
Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: relation "guacamole_user" does not exist
```

and I find that init/initdb.sql is 0 byte.
```
2020-03-19 09:22:33 [chchang@zorin guacamole-docker-compose]$ ls init/ -lart
總計 8
drwxr-xr-x 2 chchang chchang 4096  3月 19 09:08 .
-rwxr-xr-x 1 chchang chchang    0  3月 19 09:21 initdb.sql
drwxr-xr-x 8 chchang chchang 4096  3月 19 09:21 ..
2020-03-19 09:22:35 [chchang@zorin guacamole-docker-compose]$ 
```
I dont know what's the matter , and have no idea how to solve 
any sugestions ?

**Comment by boschkundendienst** [comment]
Hi, I can not reproduce your problems.

I tested my HowTo on Arch Linux 5.5.9 with docker-compose 1.25.4 and docker 19.03.8-ce.

I cloned the repo, ran `./prepare.sh`. Then `docker-compose -d`.

I stopped my firewall, and could then connect to https://127.0.0.1:8443 without any problems.

Maybe try to disable your firewall temporarily and test. if it works check how to to configure your firewall properly.

Did you really start from scratch or do you maybe have an existing database for guacamole that is not current?

Regards
Peter

**Comment by XiovV** [comment]
Same issue. I cloned the repo, ran ./prepare.sh. Then docker-compose -d and in the logs I saw `ERROR: relation "guacamole_user" does not exist`

**Comment by boschkundendienst** [comment]
Hi XiovV, you must provide more information. I am very sure, that this is a problem on your side. Please provide information about the docker and docker-compose version and your operating system. Also post the output of `docker images` and `docker ps -a`. 
Regards
Peter

**Comment by XiovV** [comment]
Docker version 19.03.6-rc2, build 97049ac8a1
docker-compose version 1.21.0, build unknown
docker images:
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
linuxserver/jellyfin         latest              34f9a4dc36d5        10 days ago         487MB
postgres                     latest              73119b8892f9        2 weeks ago         314MB
nginx                        latest              6678c7c2e56c        2 weeks ago         127MB
mysql                        latest              9b51d9275906        2 weeks ago         547MB
linuxserver/calibre-web      latest              6d6d2521e5fc        3 weeks ago         391MB
mariadb                      10.1                b6e091bb98f3        4 weeks ago         352MB
postgres                     11-alpine           b41b79676e63        5 weeks ago         152MB
mariadb                      latest              1f9cfa8dc305        7 weeks ago         356MB
guacamole/guacamole          latest              143a104965d1        7 weeks ago         500MB
guacamole/guacd              latest              592ed7aa9208        7 weeks ago         489MB
linuxserver/jellyfin         <none>              8a480b085cf2        7 weeks ago         412MB
nextcloud                    latest              4f97742686b1        8 weeks ago         724MB
linuxserver/transmission     latest              40d296694e19        8 weeks ago         80.4MB
technosoft2000/calibre-web   latest              39d7ea6665fe        2 months ago        1.04GB
portainer/portainer          latest              ff4ee4caaa23        3 months ago        81.6MB
seafileltd/seafile-mc        latest              f3349e98028e        5 months ago        799MB
memcached                    1.5.6               855fdf342eda        2 years ago         58.6MB


sudo docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                        NAMES
825f5188a2bd        nginx                        "/bin/bash -c 'nginx…"   11 hours ago        Up 11 hours         80/tcp, 0.0.0.0:8443->443/tcp                                                nginx_guacamole_compose
d078066586e2        guacamole/guacamole          "/opt/guacamole/bin/…"   11 hours ago        Up 11 hours         0.0.0.0:32768->8080/tcp                                                      guacamole_compose
8820f5d42c82        postgres                     "docker-entrypoint.s…"   11 hours ago        Up 11 hours         5432/tcp                                                                     postgres_guacamole_compose
fe4e57d3d5db        guacamole/guacd              "/bin/sh -c '/usr/lo…"   11 hours ago        Up 11 hours         4822/tcp                                                                     guacd_compose
d60ef6648e69        linuxserver/jellyfin         "/init"                  4 days ago          Up 4 days           0.0.0.0:8096->8096/tcp, 8920/tcp                                             jellyfin
f41148ac2a57        technosoft2000/calibre-web   "/bin/bash -c /init/…"   3 weeks ago         Up 5 days           0.0.0.0:5001->8083/tcp                                                       calibre-web
aa80de35ea78        postgres:11-alpine           "docker-entrypoint.s…"   4 weeks ago         Created                                                                                          actix-todo_postgres_1
f954bb52450d        linuxserver/transmission     "/init"                  7 weeks ago         Up 5 days           0.0.0.0:9091->9091/tcp, 0.0.0.0:51413->51413/tcp, 0.0.0.0:51413->51413/udp   transmission
a7260d076d2b        nextcloud                    "/entrypoint.sh apac…"   7 weeks ago         Up 5 days           0.0.0.0:4000->80/tcp                                                         nextcloud-compose_app_1
9d5de80c5f24        mariadb                      "docker-entrypoint.s…"   7 weeks ago         Up 5 days           3306/tcp                                                                     maria-db
eb5ff9361c8e        portainer/portainer          "/portainer"             7 weeks ago         Up 5 days           0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp                               portainer

**Comment by boschkundendienst** [comment]
Hi,
since this repo is really just putting together all pieces of guacamole, postgres and nginx using docker-compose. I think it must be something on your machine, maybe an existing guacamole database within an existing instance of postgres not having the latest db scheme updates applied or something like this.

What I am trying to say is, that the problem you have most likely is not related to this repo.

When starting from scratch (no existing containers and no existing docker images) I am pretty sure it will work.

**Comment by penguine** [comment]
I have had the same problem. I have run docker as sudo. So that the sql-script  /init/initdb.sql was empty. 
you can put in prepare.sh "sudo docker" as command or prepare docker to run as a normal user.
then clear all your docker images and run docker-compose again.

**Comment by boschkundendienst** [comment]
yeah that sounds logical. you should not run docker as root or with sudo. you should add your user to the docker group instead.

**Comment by superuser5** [comment]
Hello,
thank you for putting it together, i have experienced same problem and tried troubleshooting could not find the problem.

i installed it on the fresh Ubuntu 20.04 EC2 instance.

Here more info:
**step 1: install docker** 
apt install docker-compose

**step2: configure docker account**
I add docker user to the group:
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker 

**step 3: test docker**
and tested  docker run hello-world, no error messages here.

**step 4: install guac**
git clone "https://github.com/boschkundendienst/guacamole-docker-compose.git"
cd guacamole-docker-compose
./prepare.sh
docker-compose up -d

**step 5: modify docker-compose.yml**
uncomment: - 8080:8080/tcp
comment:     - 8080/tcp

**step 6:** access guac http://10.1.1.100:8080/guacamole/#/ and getting error message from guacamole server

An error has occurred and this action cannot be completed. If the problem persists, please notify your system administrator or check your system logs.


**logs:**

**$ docker images**
REPOSITORY            TAG       IMAGE ID       CREATED       SIZE
guacamole/guacd       latest    21478eb094d9   4 hours ago   271MB
guacamole/guacamole   latest    f0725609025a   6 hours ago   599MB
postgres              latest    6ce504119cc8   2 days ago    374MB
nginx                 latest    f8f4ffc8092c   4 days ago    133MB
hello-world           latest    feb5d9fea6a5   9 days ago    13.3kB

**$ docker ps -a**
CONTAINER ID   IMAGE                 COMMAND                  CREATED          STATUS                          PORTS                                       NAMES
f1c1adc5a2b1   nginx                 "/docker-entrypoint.…"   10 minutes ago   Restarting (1) 55 seconds ago                                               nginx_guacamole_compose
ea6d9f8f096a   guacamole/guacamole   "/opt/guacamole/bin/…"   10 minutes ago   Up 10 minutes                   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   guacamole_compose
139cb49c2f39   guacamole/guacd       "/bin/sh -c '/usr/lo…"   10 minutes ago   Up 10 minutes (healthy)         4822/tcp                                    guacd_compose
847c3d380ba8   postgres              "docker-entrypoint.s…"   10 minutes ago   Up 10 minutes                   5432/tcp                                    postgres_guacamole_compose
460d57900310   hello-world           "/hello"                 12 minutes ago   Exited (0) 12 minutes ago                                                   stupefied_perlman


/opt/guacamole-docker-compose$ docker exec -it ea6d9f8f096a  bash
root@ea6d9f8f096a:/opt/guacamole# ls
bin  cas  duo  guacamole.war  header  ldap  mysql  openid  postgresql  sqlserver  totp
root@ea6d9f8f096a:/opt/guacamole# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8005          0.0.0.0:*               LISTEN      1/java
tcp        0      0 127.0.0.11:38055        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/java
root@ea6d9f8f096a:/opt/guacamole# ls
bin  cas  duo  guacamole.war  header  ldap  mysql  openid  postgresql  sqlserver  totp


**logs from the guacamole/guacamole container**

root@ea6d9f8f096a:/usr/local/tomcat/logs# ls
catalina.2021-10-03.log  host-manager.2021-10-03.log  localhost.2021-10-03.log	localhost_access_log.2021-10-03.txt  manager.2021-10-03.log
root@ea6d9f8f096a:/usr/local/tomcat/logs# more manager.2021-10-03.log
root@ea6d9f8f096a:/usr/local/tomcat/logs# more localhost_access_log.2021-10-03.txt
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole HTTP/1.1" 302 -
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/app.css?v=1.3.0 HTTP/1.1" 200 61442
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/webjars/angular/1.6.9/angular.min.js HTTP/1.1" 200 73812
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/app.js?v=1.3.0 HTTP/1.1" 200 373096
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/images/warning.png HTTP/1.1" 200 1059
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/api/patches HTTP/1.1" 200 352
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/api/languages HTTP/1.1" 200 220
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "GET /guacamole/translations/en.json HTTP/1.1" 200 47045
10.8.8.11 - - [03/Oct/2021:06:30:31 +0000] "POST /guacamole/api/tokens HTTP/1.1" 500 214
root@ea6d9f8f096a:/usr/local/tomcat/logs# more localhost.2021-10-03.log
root@ea6d9f8f096a:/usr/local/tomcat/logs# more host-manager.2021-10-03.log
root@ea6d9f8f096a:/usr/local/tomcat/logs# more catalina.2021-10-03.log
03-Oct-2021 06:30:11.500 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.71
03-Oct-2021 06:30:11.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2021 18:43:14 UTC
03-Oct-2021 06:30:11.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.71.0
03-Oct-2021 06:30:11.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.11.0-1019-aws
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_302-b08
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
03-Oct-2021 06:30:11.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
03-Oct-2021 06:30:11.506 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
03-Oct-2021 06:30:11.506 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
03-Oct-2021 06:30:11.506 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
03-Oct-2021 06:30:11.506 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
03-Oct-2021 06:30:11.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
03-Oct-2021 06:30:11.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
03-Oct-2021 06:30:11.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
03-Oct-2021 06:30:11.507 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
03-Oct-2021 06:30:11.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
03-Oct-2021 06:30:11.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
03-Oct-2021 06:30:11.513 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
03-Oct-2021 06:30:11.513 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
03-Oct-2021 06:30:11.513 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
03-Oct-2021 06:30:11.519 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1k  25 Mar 2021]
03-Oct-2021 06:30:11.682 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
03-Oct-2021 06:30:11.704 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
03-Oct-2021 06:30:11.739 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1501 ms
03-Oct-2021 06:30:11.787 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
03-Oct-2021 06:30:11.787 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.71]
03-Oct-2021 06:30:11.817 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/guacamole.war]
03-Oct-2021 06:30:14.163 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no T
LDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
03-Oct-2021 06:30:17.597 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.RESTExceptionMapper as a provider class
03-Oct-2021 06:30:17.598 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.extension.ExtensionRESTService as a root resource class
03-Oct-2021 06:30:17.600 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.language.LanguageRESTService as a root resource class
03-Oct-2021 06:30:17.600 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.patch.PatchRESTService as a root resource class
03-Oct-2021 06:30:17.600 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.auth.TokenRESTService as a root resource class
03-Oct-2021 06:30:17.601 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.apache.guacamole.rest.session.SessionRESTService as a root resource class
03-Oct-2021 06:30:17.601 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.register Registering org.codehaus.jackson.jaxrs.JacksonJsonProvider as a provider class
03-Oct-2021 06:30:17.613 INFO [localhost-startStop-1] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.17.1 02/28/2013 12:47 PM'
03-Oct-2021 06:30:17.716 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.RESTExceptionMapper to GuiceManagedComponentProvider with the scope "Singleton
"
03-Oct-2021 06:30:17.718 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.codehaus.jackson.jaxrs.JacksonJsonProvider to GuiceManagedComponentProvider with the scope "Singleto
n"
03-Oct-2021 06:30:18.297 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.extension.ExtensionRESTService to GuiceManagedComponentProvider with the scope
 "PerRequest"
03-Oct-2021 06:30:18.303 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.language.LanguageRESTService to GuiceManagedComponentProvider with the scope "
PerRequest"
03-Oct-2021 06:30:18.304 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.patch.PatchRESTService to GuiceManagedComponentProvider with the scope "PerReq
uest"
03-Oct-2021 06:30:18.308 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.auth.TokenRESTService to GuiceManagedComponentProvider with the scope "PerRequ
est"
03-Oct-2021 06:30:18.309 INFO [localhost-startStop-1] com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory.getComponentProvider Binding org.apache.guacamole.rest.session.SessionRESTService to GuiceManagedComponentProvider with the scope "Pe
rRequest"
03-Oct-2021 06:30:18.327 INFO [localhost-startStop-1] org.webjars.servlet.WebjarsServlet.init WebjarsServlet initialization completed
03-Oct-2021 06:30:18.456 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/guacamole.war] has finished in [6,639] ms
03-Oct-2021 06:30:18.465 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
03-Oct-2021 06:30:18.474 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 6734 ms
root@ea6d9f8f096a:/usr/local/tomcat/logs#

**Comment by boschkundendienst** [comment]
I could reproduce your problem. It seems that the latest Postgres Official Image is not working with Guacamole. I could fix it by changinge one line in `docker-compose.yml`:

Change the line

```
image: postgres
```

to

```
image: postgres:13.4
```

You have to reset everything with `reset.sh` and again to a `prepare.sh`.

I updated the repo to reflect this.

**Comment by jorbig** [comment]
@boschkundendienst: I have the same issue with Guacamole 1.4.0, and using Postgres 13.4 didn't fix it for me:
`ERROR:  relation "guacamole_user" does not exist at character 543`

How to fix this?

**Comment by Alexxxer** [comment]
for your database running you need initializing script.
`docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --postgres > initdb.sql` will generate one.
