### ISSUE TITLE
ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by ostrolucky** [boschkundendienst/guacamole-docker-compose#91]
I repeatedly keep getting this
<img width="1335" alt="image" src="https://github.com/boschkundendienst/guacamole-docker-compose/assets/496233/468bac7e-d947-4100-89e9-5d105cb6b16f">

docker compose logs say	
```
guacamole_compose           | 12:19:17.622 [http-nio-8080-exec-8] ERROR o.a.g.s.GuacamoleHTTPTunnelServlet - HTTP tunnel request failed: java.net.ConnectException: Connection refused (Connection refused)
guacamole_compose           | 12:19:22.045 [http-nio-8080-exec-1] ERROR o.a.g.w.GuacamoleWebSocketTunnelEndpoint - Creation of WebSocket tunnel to guacd failed: java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by m3tc0n** [comment]
I'm getting the same error. Do you have a solution yet?

**Comment by ostrolucky** [comment]
Issue was that when adding connection I was accidentally filling in "Remote desktop gateway" section.

**Comment by m3tc0n** [comment]
OK, that doesn't help me. I filles in the 'network parameters' but I still get this error. It worked just fine for a couple of weeks ago.

**Comment by boschkundendienst** [comment]
I did a quick test and everything works as expected. Based on your error message it seems there is some internal communication problem. Are you maybe running SELinux or something which might prevent internal connections between the containers. And just to ask did you try this with a brandnew setup or are you struggling with your existing one? Anyways, this project ist not here to be run in production!
