### ISSUE TITLE
ssh root synology

### ISSUE THREAD

**Issue by sahara101** [boschkundendienst/guacamole-docker-compose#92]
Hey,

any idea why if I try a ssh key login to root to  a synology nas guacamole only shows 'Connected to guacamole. Waiting for response...?'

Doing this outside of guacamole is working without issues.

Thanks!

**Comment by boschkundendienst** [comment]
Hi this absoletly falls not in the range of this project but I could think of an outdated SSH server version on the Synology that uses weak ciphers. Newer SSH clients won't connect then. It can be that Guacamole uses a new one and therefor will fail. But please check that with the Guacamole team. I only provide a repo for easy test setup of the project and it is not related to the official Guacamole project at all.
