### ISSUE TITLE
no recording

### ISSUE THREAD

**Issue by GillesRonsin** [boschkundendienst/guacamole-docker-compose#94]
Hi,
I was not able to record any session.
the /record folder is not filled
I have tried many different configurations.
some message about guacamole-history-recording-storage module talk about make a directory 
**sudo mkdir -p /var/lib/guacamole/recordings**

but in guacamole container we don't have sudo password
any advice ?

**Comment by boschkundendienst** [comment]
recording is a bit tricky. of course the container must be able to write to the local directory where you store the recordings. Also the record paths must be set per connection as described in the configuration here https://guacamole.apache.org/doc/0.9.10-incubating/gug/configuring-guacamole.html

I can not give you more advise. This is beyound the scope of this project. Please look at the official Guacamole docs.
